#!/usr/bin/env python3

## @file db_params.py
#
## Adapted by @author Kalea Holdren <kalea.holdren@whoi.edu>
## Adapted by @author Mahi Sarwar Anol <anol.mahi@gmail.com> 
#
## Everything is Adapted from params.py in crocolakeloader (https://github.com/boom-lab/crocolakeloader.git)
#  Originally written by @author enrico <enrico.milanese@whoi.edu>
#
## @date Monday 4 August 2026

##########################################################################
import copy
#
# Module containing the `params` dict (per-database parameter lists and
# rename maps). Moved out of params.py (see boom-lab/crocolaketools#52).

params = {}

#------------------------------------------------------------------------------#
# CROCOLAKE
#
# standardized names for merged database
#
# _QC dictionary contains a reduced set of parameters and is used for CrocoLake's
# QC-ed only version; ideally, this is always the target dictionary to use
#
# _ALL dictionary contains all parameters and is used for CrocoLake's full
# version; ideally, this is needed only for Argo data (and maybe not at all, see
# Argo dictionaries later in file)
#
params["CROCOLAKE_PHY_QC"] = [
    'DB_NAME',
    'PLATFORM_NUMBER',
    'CYCLE_NUMBER',
    'DATA_MODE',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'JULD',
    'DEPTH',
    'PRES',
    'PRES_QC',
    'PRES_ERROR',
    'TEMP',
    'TEMP_QC',
    'TEMP_ERROR',
    'PSAL',
    'PSAL_QC',
    'PSAL_ERROR'
]

params["CROCOLAKE_PHY_ALL"] = [
    'DB_NAME',
    'PLATFORM_NUMBER',
    'CYCLE_NUMBER',
    'DATA_MODE',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'JULD',
    'DEPTH',
    'PRES',
    'PRES_QC',
    'PRES_ADJUSTED',
    'PRES_ADJUSTED_QC',
    'PRES_ADJUSTED_ERROR',
    'TEMP',
    'TEMP_QC',
    'TEMP_ADJUSTED',
    'TEMP_ADJUSTED_QC',
    'TEMP_ADJUSTED_ERROR',
    'PSAL',
    'PSAL_QC',
    'PSAL_ADJUSTED',
    'PSAL_ADJUSTED_QC',
    'PSAL_ADJUSTED_ERROR'
]

params["CROCOLAKE_BGC_QC"] = [
    'DB_NAME',
    'PLATFORM_NUMBER',
    'CYCLE_NUMBER',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'JULD',
    'DEPTH',
    'PRES',
    'PRES_QC',
    'PRES_ERROR',
    'PRES_DATA_MODE',
    'TEMP',
    'TEMP_QC',
    'TEMP_ERROR',
    'TEMP_DATA_MODE',
    'PSAL',
    'PSAL_QC',
    'PSAL_ERROR',
    'PSAL_DATA_MODE',
    'DOXY',
    'DOXY_QC',
    'DOXY_ERROR',
    'DOXY_DATA_MODE',
    'BBP',
    'BBP_QC',
    'BBP_ERROR',
    'BBP_DATA_MODE',
    'BBP470',
    'BBP470_QC',
    'BBP470_ERROR',
    'BBP470_DATA_MODE',
    'BBP532',
    'BBP532_QC',
    'BBP532_ERROR',
    'BBP532_DATA_MODE',
    'BBP700',
    'BBP700_QC',
    'BBP700_ERROR',
    'BBP700_DATA_MODE',
    'TURBIDITY',
    'TURBIDITY_QC',
    'TURBIDITY_ERROR',
    'TURBIDITY_DATA_MODE',
    'CP',
    'CP_QC',
    'CP_ERROR',
    'CP_DATA_MODE',
    'CP660',
    'CP660_QC',
    'CP660_ERROR',
    'CP660_DATA_MODE',
    'CHLA',
    'CHLA_QC',
    'CHLA_ERROR',
    'CHLA_DATA_MODE',
    'CDOM',
    'CDOM_QC',
    'CDOM_ERROR',
    'CDOM_DATA_MODE',
    'NITRATE',
    'NITRATE_QC',
    'NITRATE_ERROR',
    'NITRATE_DATA_MODE',
    'BISULFIDE',
    'BISULFIDE_QC',
    'BISULFIDE_ERROR',
    'BISULFIDE_DATA_MODE',
    'PH_IN_SITU_TOTAL',
    'PH_IN_SITU_TOTAL_QC',
    'PH_IN_SITU_TOTAL_ERROR',
    'PH_IN_SITU_TOTAL_DATA_MODE',
    'DOWN_IRRADIANCE',
    'DOWN_IRRADIANCE_QC',
    'DOWN_IRRADIANCE_ERROR',
    'DOWN_IRRADIANCE_DATA_MODE',
    'DOWN_IRRADIANCE380',
    'DOWN_IRRADIANCE380_QC',
    'DOWN_IRRADIANCE380_ERROR',
    'DOWN_IRRADIANCE380_DATA_MODE',
    'DOWN_IRRADIANCE412',
    'DOWN_IRRADIANCE412_QC',
    'DOWN_IRRADIANCE412_ERROR',
    'DOWN_IRRADIANCE412_DATA_MODE',
    'DOWN_IRRADIANCE443',
    'DOWN_IRRADIANCE443_QC',
    'DOWN_IRRADIANCE443_ERROR',
    'DOWN_IRRADIANCE443_DATA_MODE',
    'DOWN_IRRADIANCE490',
    'DOWN_IRRADIANCE490_QC',
    'DOWN_IRRADIANCE490_ERROR',
    'DOWN_IRRADIANCE490_DATA_MODE',
    'DOWN_IRRADIANCE555',
    'DOWN_IRRADIANCE555_QC',
    'DOWN_IRRADIANCE555_ERROR',
    'DOWN_IRRADIANCE555_DATA_MODE',
    'UP_IRRADIANCE',
    'UP_IRRADIANCE_QC',
    'UP_IRRADIANCE_ERROR',
    'UP_IRRADIANCE_DATA_MODE',
    'UP_IRRADIANCE380',
    'UP_IRRADIANCE380_QC',
    'UP_IRRADIANCE380_ERROR',
    'UP_IRRADIANCE380_DATA_MODE',
    'UP_IRRADIANCE412',
    'UP_IRRADIANCE412_QC',
    'UP_IRRADIANCE412_ERROR',
    'UP_IRRADIANCE412_DATA_MODE',
    'UP_IRRADIANCE443',
    'UP_IRRADIANCE443_QC',
    'UP_IRRADIANCE443_ERROR',
    'UP_IRRADIANCE443_DATA_MODE',
    'UP_IRRADIANCE490',
    'UP_IRRADIANCE490_QC',
    'UP_IRRADIANCE490_ERROR',
    'UP_IRRADIANCE490_DATA_MODE',
    'UP_IRRADIANCE555',
    'UP_IRRADIANCE555_QC',
    'UP_IRRADIANCE555_ERROR',
    'UP_IRRADIANCE555_DATA_MODE',
    'DOWNWELLING_PAR',
    'DOWNWELLING_PAR_QC',
    'DOWNWELLING_PAR_ERROR',
    'DOWNWELLING_PAR_DATA_MODE',
    'SILICATE',
    'SILICATE_QC',
    'SILICATE_ERROR',
    'SILICATE_DATA_MODE',
    'PHOSPHATE',
    'PHOSPHATE_QC',
    'PHOSPHATE_ERROR',
    'PHOSPHATE_DATA_MODE',
    'TCO2',
    'TCO2_QC',
    'TCO2_ERROR',
    'TCO2_DATA_MODE',
    'TOT_ALKALINITY',
    'TOT_ALKALINITY_QC',
    'TOT_ALKALINITY_ERROR',
    'TOT_ALKALINITY_DATA_MODE',
    'CFC11',
    'CFC11_QC',
    'CFC11_ERROR',
    'CFC11_DATA_MODE',
    'CFC12',
    'CFC12_QC',
    'CFC12_ERROR',
    'CFC12_DATA_MODE',
    'CFC113',
    'CFC113_QC',
    'CFC113_ERROR',
    'CFC113_DATA_MODE',
    'CCL4',
    'CCL4_QC',
    'CCL4_ERROR',
    'CCL4_DATA_MODE',
    'SF6',
    'SF6_QC',
    'SF6_ERROR',
    'SF6_DATA_MODE',
]

params["CROCOLAKE_BGC_ALL"] = [
    'DB_NAME',
    'PLATFORM_NUMBER',
    'CYCLE_NUMBER',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'JULD',
    'DEPTH',
    'PRES',
    'PRES_QC',
    'PRES_ADJUSTED',
    'PRES_ADJUSTED_QC',
    'PRES_ADJUSTED_ERROR',
    'PRES_DATA_MODE',
    'TEMP',
    'TEMP_QC',
    'TEMP_ADJUSTED',
    'TEMP_ADJUSTED_QC',
    'TEMP_ADJUSTED_ERROR',
    'TEMP_DATA_MODE',
    'PSAL',
    'PSAL_QC',
    'PSAL_ADJUSTED',
    'PSAL_ADJUSTED_QC',
    'PSAL_ADJUSTED_ERROR',
    'PSAL_DATA_MODE',
    'DOXY',
    'DOXY_QC',
    'DOXY_ADJUSTED',
    'DOXY_ADJUSTED_QC',
    'DOXY_ADJUSTED_ERROR',
    'DOXY_DATA_MODE',
    'BBP',
    'BBP_QC',
    'BBP_ADJUSTED',
    'BBP_ADJUSTED_QC',
    'BBP_ADJUSTED_ERROR',
    'BBP_DATA_MODE',
    'BBP470',
    'BBP470_QC',
    'BBP470_ADJUSTED',
    'BBP470_ADJUSTED_QC',
    'BBP470_ADJUSTED_ERROR',
    'BBP470_DATA_MODE',
    'BBP532',
    'BBP532_QC',
    'BBP532_ADJUSTED',
    'BBP532_ADJUSTED_QC',
    'BBP532_ADJUSTED_ERROR',
    'BBP532_DATA_MODE',
    'BBP700',
    'BBP700_QC',
    'BBP700_ADJUSTED',
    'BBP700_ADJUSTED_QC',
    'BBP700_ADJUSTED_ERROR',
    'BBP700_DATA_MODE',
    'TURBIDITY',
    'TURBIDITY_QC',
    'TURBIDITY_ADJUSTED',
    'TURBIDITY_ADJUSTED_QC',
    'TURBIDITY_ADJUSTED_ERROR',
    'TURBIDITY_DATA_MODE',
    'CP',
    'CP_QC',
    'CP_ADJUSTED',
    'CP_ADJUSTED_QC',
    'CP_ADJUSTED_ERROR',
    'CP_DATA_MODE',
    'CP660',
    'CP660_QC',
    'CP660_ADJUSTED',
    'CP660_ADJUSTED_QC',
    'CP660_ADJUSTED_ERROR',
    'CP660_DATA_MODE',
    'CHLA',
    'CHLA_QC',
    'CHLA_ADJUSTED',
    'CHLA_ADJUSTED_QC',
    'CHLA_ADJUSTED_ERROR',
    'CHLA_DATA_MODE',
    'CDOM',
    'CDOM_QC',
    'CDOM_ADJUSTED',
    'CDOM_ADJUSTED_QC',
    'CDOM_ADJUSTED_ERROR',
    'CDOM_DATA_MODE',
    'NITRATE',
    'NITRATE_QC',
    'NITRATE_ADJUSTED',
    'NITRATE_ADJUSTED_QC',
    'NITRATE_ADJUSTED_ERROR',
    'NITRATE_DATA_MODE',
    'BISULFIDE',
    'BISULFIDE_QC',
    'BISULFIDE_ADJUSTED',
    'BISULFIDE_ADJUSTED_QC',
    'BISULFIDE_ADJUSTED_ERROR',
    'BISULFIDE_DATA_MODE',
    'PH_IN_SITU_TOTAL',
    'PH_IN_SITU_TOTAL_QC',
    'PH_IN_SITU_TOTAL_ADJUSTED',
    'PH_IN_SITU_TOTAL_ADJUSTED_QC',
    'PH_IN_SITU_TOTAL_ADJUSTED_ERROR',
    'PH_IN_SITU_TOTAL_DATA_MODE',
    'DOWN_IRRADIANCE',
    'DOWN_IRRADIANCE_QC',
    'DOWN_IRRADIANCE_ADJUSTED',
    'DOWN_IRRADIANCE_ADJUSTED_QC',
    'DOWN_IRRADIANCE_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE_DATA_MODE',
    'DOWN_IRRADIANCE380',
    'DOWN_IRRADIANCE380_QC',
    'DOWN_IRRADIANCE380_ADJUSTED',
    'DOWN_IRRADIANCE380_ADJUSTED_QC',
    'DOWN_IRRADIANCE380_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE380_DATA_MODE',
    'DOWN_IRRADIANCE412',
    'DOWN_IRRADIANCE412_QC',
    'DOWN_IRRADIANCE412_ADJUSTED',
    'DOWN_IRRADIANCE412_ADJUSTED_QC',
    'DOWN_IRRADIANCE412_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE412_DATA_MODE',
    'DOWN_IRRADIANCE443',
    'DOWN_IRRADIANCE443_QC',
    'DOWN_IRRADIANCE443_ADJUSTED',
    'DOWN_IRRADIANCE443_ADJUSTED_QC',
    'DOWN_IRRADIANCE443_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE443_DATA_MODE',
    'DOWN_IRRADIANCE490',
    'DOWN_IRRADIANCE490_QC',
    'DOWN_IRRADIANCE490_ADJUSTED',
    'DOWN_IRRADIANCE490_ADJUSTED_QC',
    'DOWN_IRRADIANCE490_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE490_DATA_MODE',
    'DOWN_IRRADIANCE555',
    'DOWN_IRRADIANCE555_QC',
    'DOWN_IRRADIANCE555_ADJUSTED',
    'DOWN_IRRADIANCE555_ADJUSTED_QC',
    'DOWN_IRRADIANCE555_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE555_DATA_MODE',
    'UP_IRRADIANCE',
    'UP_IRRADIANCE_QC',
    'UP_IRRADIANCE_ADJUSTED',
    'UP_IRRADIANCE_ADJUSTED_QC',
    'UP_IRRADIANCE_ADJUSTED_ERROR',
    'UP_IRRADIANCE_DATA_MODE',
    'UP_IRRADIANCE380',
    'UP_IRRADIANCE380_QC',
    'UP_IRRADIANCE380_ADJUSTED',
    'UP_IRRADIANCE380_ADJUSTED_QC',
    'UP_IRRADIANCE380_ADJUSTED_ERROR',
    'UP_IRRADIANCE380_DATA_MODE',
    'UP_IRRADIANCE412',
    'UP_IRRADIANCE412_QC',
    'UP_IRRADIANCE412_ADJUSTED',
    'UP_IRRADIANCE412_ADJUSTED_QC',
    'UP_IRRADIANCE412_ADJUSTED_ERROR',
    'UP_IRRADIANCE412_DATA_MODE',
    'UP_IRRADIANCE443',
    'UP_IRRADIANCE443_QC',
    'UP_IRRADIANCE443_ADJUSTED',
    'UP_IRRADIANCE443_ADJUSTED_QC',
    'UP_IRRADIANCE443_ADJUSTED_ERROR',
    'UP_IRRADIANCE443_DATA_MODE',
    'UP_IRRADIANCE490',
    'UP_IRRADIANCE490_QC',
    'UP_IRRADIANCE490_ADJUSTED',
    'UP_IRRADIANCE490_ADJUSTED_QC',
    'UP_IRRADIANCE490_ADJUSTED_ERROR',
    'UP_IRRADIANCE490_DATA_MODE',
    'UP_IRRADIANCE555',
    'UP_IRRADIANCE555_QC',
    'UP_IRRADIANCE555_ADJUSTED',
    'UP_IRRADIANCE555_ADJUSTED_QC',
    'UP_IRRADIANCE555_ADJUSTED_ERROR',
    'UP_IRRADIANCE555_DATA_MODE',
    'DOWNWELLING_PAR',
    'DOWNWELLING_PAR_QC',
    'DOWNWELLING_PAR_ADJUSTED',
    'DOWNWELLING_PAR_ADJUSTED_QC',
    'DOWNWELLING_PAR_ADJUSTED_ERROR',
    'DOWNWELLING_PAR_DATA_MODE',
    'SILICATE',
    'SILICATE_QC',
    'SILICATE_ERROR',
    'SILICATE_DATA_MODE',
    'PHOSPHATE',
    'PHOSPHATE_QC',
    'PHOSPHATE_ERROR',
    'PHOSPHATE_DATA_MODE',
    'TCO2',
    'TCO2_QC',
    'TCO2_ERROR',
    'TCO2_DATA_MODE',
    'TOT_ALKALINITY',
    'TOT_ALKALINITY_QC',
    'TOT_ALKALINITY_ERROR',
    'TOT_ALKALINITY_DATA_MODE',
    'CFC11',
    'CFC11_QC',
    'CFC11_ERROR',
    'CFC11_DATA_MODE',
    'CFC12',
    'CFC12_QC',
    'CFC12_ERROR',
    'CFC12_DATA_MODE',
    'CFC113',
    'CFC113_QC',
    'CFC113_ERROR',
    'CFC113_DATA_MODE',
    'CCL4',
    'CCL4_QC',
    'CCL4_ERROR',
    'CCL4_DATA_MODE',
    'SF6',
    'SF6_QC',
    'SF6_ERROR',
    'SF6_DATA_MODE',
]



#------------------------------------------------------------------------------#
# GLODAP
#
# original names of parameters to keep

params["GLODAP"] = [
    'year', 'month', 'day', 'hour', 'minute',
    'latitude', 'longitude', 'pressure', 'temperature', 'salinity',
    'oxygen', 'nitrate', 'silicate', 'phosphate', 'tco2', 'talk',
    'phtsinsitutp', 'cfc11', 'cfc12', 'cfc113', 'ccl4', 'sf6', 'chla',
]

#
# dict for renaming parameters to crocolake names
#
params["GLODAP2CROCOLAKE"] = {
    'expocode' : 'PLATFORM_NUMBER',
    'latitude' : 'LATITUDE',
    'longitude' : 'LONGITUDE',
    'pressure' : 'PRES',
    'temperature' : 'TEMP',
    'salinity' : 'PSAL',
    'oxygen' : 'DOXY',
    'nitrate' : 'NITRATE',
    'silicate' : 'SILICATE',
    'phosphate' : 'PHOSPHATE',
    'tco2' : 'TCO2',
    'talk' : 'TOT_ALKALINITY',
    'phtsinsitutp' : 'PH_IN_SITU_TOTAL',
    'cfc11' : 'CFC11',
    'cfc12' : 'CFC12',
    'cfc113' : 'CFC113',
    'ccl4' : 'CCL4',
    'sf6' : 'SF6',
    'chla' : 'CHLA',
    'salinityf' : 'PSAL_QC',
    'oxygenf' : 'DOXY_QC',
    'nitratef' : 'NITRATE_QC',
    'silicatef' : 'SILICATE_QC',
    'phosphatef' : 'PHOSPHATE_QC',
    'tco2f' : 'TCO2_QC',
    'talkf' : 'TOT_ALKALINITY_QC',
    'phtsinsitutpf' : 'PH_IN_SITU_TOTAL_QC',
    'cfc11f' : 'CFC11_QC',
    'cfc12f' : 'CFC12_QC',
    'cfc113f' : 'CFC113_QC',
    'ccl4f' : 'CCL4_QC',
    'sf6f' : 'SF6_QC',
    'chlaf' : 'CHLA_QC',
    'profile_nb' : 'CYCLE_NUMBER', # temporary name for profile ID, this is
                                   # created in the converter, it is not in the
                                   # original csv file
    'date_update' : 'DATE_UPDATE', # temporary name for date update
}

#------------------------------------------------------------------------------#
# Spray Gliders
#
# original names of parameters to keep

params['SprayGliders'] = [
    'depth',
    'profile',
    'lat',
    'lon',
    'time',
    'mission_name',
    'mission',
    'salinity',
    'sal',
    'temperature',
    'temp',
    'chlorophyll_a',
    'doxy'
]

#
# dict for renaming parameters to crocolake names
#
params["SprayGliders2CROCOLAKE"] = {
    'mission' : 'PLATFORM_NUMBER',
    'profile': 'CYCLE_NUMBER',
    'depth': 'DEPTH',
    'lat' : 'LATITUDE',
    'lon' : 'LONGITUDE',
    'temperature' : 'TEMP',
    'temp' : 'TEMP',
    'salinity' : 'PSAL',
    'sal' : 'PSAL',
    'time': 'JULD',
    'chlorophyll_a' : 'CHLA',
    'doxy' : 'DOXY',
    'date_update' : 'DATE_UPDATE', # temporary name for date update
}

params["CROCOLAKE2SprayGliders"] = {v: k for k, v in
                                    params["SprayGliders2CROCOLAKE"].items()}

#------------------------------------------------------------------------------#
# CPR (Continuous Plankton Recorder)
#
# original names of parameters to keep

params['CPR'] = [
    'SampleId',
    'Latitude',
    'Longitude',
    'MidPoint_Date_UTC',
    'Year',
    'Month',
    'Day',
    'Hour'
]

#
# dict for renaming parameters to crocolake names
#
params["CPR2CROCOLAKE"] = {
    'SampleId' : 'PLATFORM_NUMBER',
    'Latitude' : 'LATITUDE',
    'Longitude' : 'LONGITUDE',
    'MidPoint_Date_UTC' : 'JULD'
}


#------------------------------------------------------------------------------#
# Saildrones
#
# original names of parameters to keep
#
params["Saildrones"] = [
    'wmo_id',
    'latitude',
    'longitude',
    'time',
    'TEMP_SBE37_MEAN',
    'TEMP_CTD_MEAN',
    'TEMP_CTD_RBR_MEAN',
    'TEMP_DEPTH_HALFMETER_MEAN',
    'SAL_SBE37_MEAN',
    'SAL_RBR_MEAN',
    'SAL_MEAN',
    'O2_CONC_SBE37_MEAN',
    'O2_CONC_MEAN',
    'O2_CONC_UNCOR_MEAN',
    'O2_RBR_CONC_MEAN',
    'O2_CONC_RBR_MEAN',
    'O2_AANDERAA_CONC_UNCOR_MEAN',
    'O2_CONC_AANDERAA_MEAN',
    'CHLOR_WETLABS_MEAN',
    'CHLOR_RBR_MEAN',
    'CHLOR_MEAN',
    'CDOM_MEAN',
    'BKSCT_RED_MEAN',
    'TEMP_SBE37_STDDEV',
    'TEMP_CTD_STDDEV',
    'TEMP_DEPTH_HALFMETER_STDDEV',
    'SAL_SBE37_STDDEV',
    'SAL_RBR_STDDEV',
    'SAL_STDDEV',
    'O2_CONC_SBE37_STDDEV',
    'O2_CONC_STDDEV',
    'O2_CONC_UNCOR_STDDEV',
    'O2_RBR_CONC_STDDEV',
    'O2_CONC_RBR_STDDEV',
    'O2_AANDERAA_CONC_UNCOR_STDDEV',
    'O2_CONC_AANDERAA_STDDEV',
    'CHLOR_WETLABS_STDDEV',
    'CHLOR_RBR_STDDEV',
    'CHLOR_STDDEV',
    'CDOM_STDDEV',
    'BKSCT_RED_STDDEV',
]

#
# dict for renaming parameters to crocolake names
#
params["Saildrones2CROCOLAKE"] = {
    'wmo_id': 'PLATFORM_NUMBER',
    'latitude': 'LATITUDE',
    'longitude': 'LONGITUDE',
    'time': 'JULD',
    'depth': 'DEPTH',
    'TEMP_CTD_MEAN': 'TEMP',
    'TEMP_CTD_RBR_MEAN': 'TEMP',
    'TEMP_SBE37_MEAN': 'TEMP',
    'TEMP_DEPTH_HALFMETER_MEAN': 'TEMP',
    'SAL_SBE37_MEAN': 'PSAL',
    'SAL_RBR_MEAN': 'PSAL',
    'SAL_MEAN': 'PSAL',
    'O2_CONC_SBE37_MEAN': 'DOXY',
    'O2_CONC_MEAN': 'DOXY',
    'O2_CONC_UNCOR_MEAN': 'DOXY',
    'O2_RBR_CONC_MEAN': 'DOXY',
    'O2_CONC_RBR_MEAN': 'DOXY',
    'O2_AANDERAA_CONC_UNCOR_MEAN': 'DOXY',
    'O2_CONC_AANDERAA_MEAN': 'DOXY',
    'CHLOR_WETLABS_MEAN': 'CHLA',
    'CHLOR_RBR_MEAN': 'CHLA',
    'CHLOR_MEAN': 'CHLA',
    'CDOM_MEAN': 'CDOM',
    'BKSCT_RED_MEAN': 'BBP700',
    'TEMP_SBE37_STDDEV': 'TEMP_ERROR',
    'TEMP_DEPTH_HALFMETER_STDDEV': 'TEMP_ERROR',
    'TEMP_CTD_STDDEV': 'TEMP_ERROR',
    'TEMP_CTD_RBR_STDDEV': 'TEMP_ERROR',
    'SAL_SBE37_STDDEV': 'PSAL_ERROR',
    'SAL_RBR_STDDEV': 'PSAL_ERROR',
    'SAL_STDDEV': 'PSAL_ERROR',
    'O2_CONC_SBE37_STDDEV': 'DOXY_ERROR',
    'O2_CONC_STDDEV': 'DOXY_ERROR',
    'O2_CONC_UNCOR_STDDEV': 'DOXY_ERROR',
    'O2_RBR_CONC_STDDEV': 'DOXY_ERROR',
    'O2_CONC_RBR_STDDEV': 'DOXY_ERROR',
    'O2_AANDERAA_CONC_UNCOR_STDDEV': 'DOXY_ERROR',
    'O2_CONC_AANDERAA_STDDEV': 'DOXY_ERROR',
    'CHLOR_WETLABS_STDDEV': 'CHLA_ERROR',
    'CHLOR_RBR_STDDEV': 'CHLA_ERROR',
    'CHLOR_STDDEV': 'CHLA_ERROR',
    'CDOM_STDDEV': 'CDOM_ERROR',
    'BKSCT_RED_STDDEV': 'BBP700_ERROR',
}

params["CROCOLAKE2Saildrones"] = {v: k for k, v in 
                                  params["Saildrones2CROCOLAKE"].items()}

#
# Saildrones data doesn't include a dedicated depth variable.
# depths are inferred from metadata associated with specific sensor variables.
#

params["Saildrones_depth_map"] = {
    "TEMP_CTD_MEAN":               0.6,
    "TEMP_CTD_RBR_MEAN":           0.53,
    "TEMP_SBE37_MEAN":             1.7,
    "TEMP_DEPTH_HALFMETER_MEAN":   0.5,
    "O2_CONC_MEAN":                0.6,
    "O2_RBR_CONC_MEAN":            0.53,
    "O2_CONC_RBR_MEAN":            0.53,
    "O2_CONC_SBE37_MEAN":          1.7,
    "O2_CONC_UNCOR_MEAN":          0.6,
    "O2_AANDERAA_CONC_UNCOR_MEAN": 0.6,
    "O2_CONC_AANDERAA_MEAN":       0.6,
    "SAL_MEAN":                    0.6,
    "SAL_RBR_MEAN":                0.53,
    "SAL_SBE37_MEAN":              1.7,
    "CHLOR_MEAN":                  0.25,
    "CHLOR_RBR_MEAN":              0.53,
    "CHLOR_WETLABS_MEAN":          1.9,
    "CDOM_MEAN":                   1.9,
    "BKSCT_RED_MEAN":              1.9,
}

# Add corresponding _STDDEV variables with same depths
params["Saildrones_depth_map"].update({k.replace("_MEAN", "_STDDEV"): v for k, v in 
                                       params["Saildrones_depth_map"].items() if "_MEAN" in k})

#------------------------------------------------------------------------------#
# OleanderXBT
#
# original names of parameters to keep
#

params["OleanderXBT"] = [
    'trajectory',
    'profile',
    'latitude',
    'longitude',
    'time',
    'depth',
    'temp',
]

#
# dict for renaming parameters to crocolake names
#
params["OleanderXBT2CROCOLAKE"] = {
    'trajectory' : 'PLATFORM_NUMBER',
    'profile' : 'CYCLE_NUMBER',
    'latitude' : 'LATITUDE',
    'longitude' : 'LONGITUDE',
    'time' : 'JULD',
    'depth' : 'DEPTH',
    'temp' : 'TEMP',
}

#------------------------------------------------------------------------------#
# SPOTS
#
# original names of parameters to keep

params["SPOTS"] = [
    'TimeSeriesSite',
    'DATE',
    'TIME',
    'LATITUDE',
    'LONGITUDE',
    'CTDPRS',
    'CTDTMP',
    'CTDSAL',
    'SALNTY',
    'OXYGEN',
    'NITRAT',
    'PHSPHT',
    'SILCAT',
    'ALKALI',
    'PH_TOT',
    'SALNTY_P',
    'SALNTY_A',
    'SALNTY_FLAG_W',
    'CTDSAL_FLAG_W',
    'OXYGEN_P',
    'OXYGEN_A',
    'OXYGEN_FLAG_W',
    'NITRAT_P',
    'NITRAT_A',
    'NITRAT_FLAG_W',
    'PHSPHT_P',
    'PHSPHT_A',
    'PHSPHT_FLAG_W',
    'SILCAT_P',
    'SILCAT_A',
    'SILCAT_FLAG_W',
    'ALKALI_P',
    'ALKALI_A',
    'ALKALI_FLAG_W',
    'PH_TOT_P',
    'PH_TOT_A',
    'PH_TOT_FLAG_W',
]

#
# dict for renaming parameters to crocolake names
#
params["SPOTS2CROCOLAKE"] = {
    'TimeSeriesSite' : 'PLATFORM_NUMBER',
    'LATITUDE' : 'LATITUDE',
    'LONGITUDE' : 'LONGITUDE',
    'CTDPRS' : 'PRES',
    'CTDTMP' : 'TEMP',
    'PSAL' : 'PSAL',
    'OXYGEN' : 'DOXY',
    'NITRAT' : 'NITRATE',
    'SILCAT' : 'SILICATE',
    'PHSPHT' : 'PHOSPHATE',
    'ALKALI' : 'TOT_ALKALINITY',
    'PH_TOT' : 'PH_IN_SITU_TOTAL',
    'PSAL_QC' : 'PSAL_QC',
    'OXYGEN_FLAG_W' : 'DOXY_QC',
    'NITRAT_FLAG_W' : 'NITRATE_QC',
    'SILCAT_FLAG_W' : 'SILICATE_QC',
    'PHSPHT_FLAG_W' : 'PHOSPHATE_QC',
    'ALKALI_FLAG_W' : 'TOT_ALKALINITY_QC',
    'PH_TOT_FLAG_W' : 'PH_IN_SITU_TOTAL_QC',
    'PSAL_ERROR' : 'PSAL_ERROR',
    'OXYGEN_ERROR' : 'DOXY_ERROR',
    'NITRAT_ERROR' : 'NITRATE_ERROR',
    'SILCAT_ERROR' : 'SILICATE_ERROR',
    'PHSPHT_ERROR' : 'PHOSPHATE_ERROR',
    'ALKALI_ERROR' : 'TOT_ALKALINITY_ERROR',
    'PH_TOT_ERROR' : 'PH_IN_SITU_TOTAL_ERROR',
    
    'profile_nb' : 'CYCLE_NUMBER', # temporary name for profile ID, this is 
                                   # created in the converter, it is not in the
                                   # original csv file
    'date_update' : 'DATE_UPDATE', # temporary name for date update
}

params["CROCOLAKE2SPOTS"] = {
    value: key for key, value in params["SPOTS2CROCOLAKE"].items()
}

#------------------------------------------------------------------------------#
# Argo
#
# standardized names for Argo only databases, when converting from GDAC
#

params["ArgoPHY"] = [
    'PLATFORM_NUMBER',
    'N_PROF',
    'N_LEVELS',
    'CYCLE_NUMBER',
    'DIRECTION',
    'DATA_MODE',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'POSITION_QC',
    'JULD',
    'JULD_QC',
    'PRES',
    'PRES_QC',
    'PRES_ADJUSTED',
    'PRES_ADJUSTED_QC',
    'PRES_ADJUSTED_ERROR',
    'TEMP',
    'TEMP_QC',
    'TEMP_ADJUSTED',
    'TEMP_ADJUSTED_QC',
    'TEMP_ADJUSTED_ERROR',
    'PSAL',
    'PSAL_QC',
    'PSAL_ADJUSTED',
    'PSAL_ADJUSTED_QC',
    'PSAL_ADJUSTED_ERROR'
]

params["ArgoBGC"] = [
    'PLATFORM_NUMBER',
    'N_PROF',
    'N_LEVELS',
    'CYCLE_NUMBER',
    'DIRECTION',
    'DATE_UPDATE',
    'LATITUDE',
    'LONGITUDE',
    'POSITION_QC',
    'JULD',
    'JULD_QC',
    'PRES',
    'PRES_QC',
    'PRES_ADJUSTED',
    'PRES_ADJUSTED_QC',
    'PRES_ADJUSTED_ERROR',
    'PRES_DATA_MODE',
    'TEMP',
    'TEMP_QC',
    'TEMP_dPRES',
    'TEMP_ADJUSTED',
    'TEMP_ADJUSTED_QC',
    'TEMP_ADJUSTED_ERROR',
    'TEMP_DATA_MODE',
    'PSAL',
    'PSAL_QC',
    'PSAL_dPRES',
    'PSAL_ADJUSTED',
    'PSAL_ADJUSTED_QC',
    'PSAL_ADJUSTED_ERROR',
    'PSAL_DATA_MODE',
    'DOXY',
    'DOXY_QC',
    'DOXY_dPRES',
    'DOXY_ADJUSTED',
    'DOXY_ADJUSTED_QC',
    'DOXY_ADJUSTED_ERROR',
    'DOXY_DATA_MODE',
    'BBP',
    'BBP_QC',
    'BBP_dPRES',
    'BBP_ADJUSTED',
    'BBP_ADJUSTED_QC',
    'BBP_ADJUSTED_ERROR',
    'BBP_DATA_MODE',
    'BBP470',
    'BBP470_QC',
    'BBP470_dPRES',
    'BBP470_ADJUSTED',
    'BBP470_ADJUSTED_QC',
    'BBP470_ADJUSTED_ERROR',
    'BBP470_DATA_MODE',
    'BBP532',
    'BBP532_QC',
    'BBP532_dPRES',
    'BBP532_ADJUSTED',
    'BBP532_ADJUSTED_QC',
    'BBP532_ADJUSTED_ERROR',
    'BBP532_DATA_MODE',
    'BBP700',
    'BBP700_QC',
    'BBP700_dPRES',
    'BBP700_ADJUSTED',
    'BBP700_ADJUSTED_QC',
    'BBP700_ADJUSTED_ERROR',
    'BBP700_DATA_MODE',
    'TURBIDITY',
    'TURBIDITY_QC',
    'TURBIDITY_dPRES',
    'TURBIDITY_ADJUSTED',
    'TURBIDITY_ADJUSTED_QC',
    'TURBIDITY_ADJUSTED_ERROR',
    'TURBIDITY_DATA_MODE',
    'CP',
    'CP_QC',
    'CP_dPRES',
    'CP_ADJUSTED',
    'CP_ADJUSTED_QC',
    'CP_ADJUSTED_ERROR',
    'CP_DATA_MODE',
    'CP660',
    'CP660_QC',
    'CP660_dPRES',
    'CP660_ADJUSTED',
    'CP660_ADJUSTED_QC',
    'CP660_ADJUSTED_ERROR',
    'CP660_DATA_MODE',
    'CHLA',
    'CHLA_QC',
    'CHLA_dPRES',
    'CHLA_ADJUSTED',
    'CHLA_ADJUSTED_QC',
    'CHLA_ADJUSTED_ERROR',
    'CHLA_DATA_MODE',
    'CHLA_FLUORESCENCE',
    'CHLA_FLUORESCENCE_QC',
    'CHLA_FLUORESCENCE_dPRES',
    'CHLA_FLUORESCENCE_ADJUSTED',
    'CHLA_FLUORESCENCE_ADJUSTED_QC',
    'CHLA_FLUORESCENCE_ADJUSTED_ERROR',
    'CHLA_FLUORESCENCE_DATA_MODE',
    'CDOM',
    'CDOM_QC',
    'CDOM_dPRES',
    'CDOM_ADJUSTED',
    'CDOM_ADJUSTED_QC',
    'CDOM_ADJUSTED_ERROR',
    'CDOM_DATA_MODE',
    'NITRATE',
    'NITRATE_QC',
    'NITRATE_dPRES',
    'NITRATE_ADJUSTED',
    'NITRATE_ADJUSTED_QC',
    'NITRATE_ADJUSTED_ERROR',
    'NITRATE_DATA_MODE',
    'BISULFIDE',
    'BISULFIDE_QC',
    'BISULFIDE_dPRES',
    'BISULFIDE_ADJUSTED',
    'BISULFIDE_ADJUSTED_QC',
    'BISULFIDE_ADJUSTED_ERROR',
    'BISULFIDE_DATA_MODE',
    'PH_IN_SITU_TOTAL',
    'PH_IN_SITU_TOTAL_QC',
    'PH_IN_SITU_TOTAL_dPRES',
    'PH_IN_SITU_TOTAL_ADJUSTED',
    'PH_IN_SITU_TOTAL_ADJUSTED_QC',
    'PH_IN_SITU_TOTAL_ADJUSTED_ERROR',
    'PH_IN_SITU_TOTAL_DATA_MODE',
    'DOWN_IRRADIANCE',
    'DOWN_IRRADIANCE_QC',
    'DOWN_IRRADIANCE_dPRES',
    'DOWN_IRRADIANCE_ADJUSTED',
    'DOWN_IRRADIANCE_ADJUSTED_QC',
    'DOWN_IRRADIANCE_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE_DATA_MODE',
    'DOWN_IRRADIANCE380',
    'DOWN_IRRADIANCE380_QC',
    'DOWN_IRRADIANCE380_dPRES',
    'DOWN_IRRADIANCE380_ADJUSTED',
    'DOWN_IRRADIANCE380_ADJUSTED_QC',
    'DOWN_IRRADIANCE380_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE380_DATA_MODE',
    'DOWN_IRRADIANCE412',
    'DOWN_IRRADIANCE412_QC',
    'DOWN_IRRADIANCE412_dPRES',
    'DOWN_IRRADIANCE412_ADJUSTED',
    'DOWN_IRRADIANCE412_ADJUSTED_QC',
    'DOWN_IRRADIANCE412_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE412_DATA_MODE',
    'DOWN_IRRADIANCE443',
    'DOWN_IRRADIANCE443_QC',
    'DOWN_IRRADIANCE443_dPRES',
    'DOWN_IRRADIANCE443_ADJUSTED',
    'DOWN_IRRADIANCE443_ADJUSTED_QC',
    'DOWN_IRRADIANCE443_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE443_DATA_MODE',
    'DOWN_IRRADIANCE490',
    'DOWN_IRRADIANCE490_QC',
    'DOWN_IRRADIANCE490_dPRES',
    'DOWN_IRRADIANCE490_ADJUSTED',
    'DOWN_IRRADIANCE490_ADJUSTED_QC',
    'DOWN_IRRADIANCE490_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE490_DATA_MODE',
    'DOWN_IRRADIANCE555',
    'DOWN_IRRADIANCE555_QC',
    'DOWN_IRRADIANCE555_dPRES',
    'DOWN_IRRADIANCE555_ADJUSTED',
    'DOWN_IRRADIANCE555_ADJUSTED_QC',
    'DOWN_IRRADIANCE555_ADJUSTED_ERROR',
    'DOWN_IRRADIANCE555_DATA_MODE',
    'UP_IRRADIANCE',
    'UP_IRRADIANCE_QC',
    'UP_IRRADIANCE_dPRES',
    'UP_IRRADIANCE_ADJUSTED',
    'UP_IRRADIANCE_ADJUSTED_QC',
    'UP_IRRADIANCE_ADJUSTED_ERROR',
    'UP_IRRADIANCE_DATA_MODE',
    'UP_IRRADIANCE380',
    'UP_IRRADIANCE380_QC',
    'UP_IRRADIANCE380_dPRES',
    'UP_IRRADIANCE380_ADJUSTED',
    'UP_IRRADIANCE380_ADJUSTED_QC',
    'UP_IRRADIANCE380_ADJUSTED_ERROR',
    'UP_IRRADIANCE380_DATA_MODE',
    'UP_IRRADIANCE412',
    'UP_IRRADIANCE412_QC',
    'UP_IRRADIANCE412_dPRES',
    'UP_IRRADIANCE412_ADJUSTED',
    'UP_IRRADIANCE412_ADJUSTED_QC',
    'UP_IRRADIANCE412_ADJUSTED_ERROR',
    'UP_IRRADIANCE412_DATA_MODE',
    'UP_IRRADIANCE443',
    'UP_IRRADIANCE443_QC',
    'UP_IRRADIANCE443_dPRES',
    'UP_IRRADIANCE443_ADJUSTED',
    'UP_IRRADIANCE443_ADJUSTED_QC',
    'UP_IRRADIANCE443_ADJUSTED_ERROR',
    'UP_IRRADIANCE443_DATA_MODE',
    'UP_IRRADIANCE490',
    'UP_IRRADIANCE490_QC',
    'UP_IRRADIANCE490_dPRES',
    'UP_IRRADIANCE490_ADJUSTED',
    'UP_IRRADIANCE490_ADJUSTED_QC',
    'UP_IRRADIANCE490_ADJUSTED_ERROR',
    'UP_IRRADIANCE490_DATA_MODE',
    'UP_IRRADIANCE555',
    'UP_IRRADIANCE555_QC',
    'UP_IRRADIANCE555_dPRES',
    'UP_IRRADIANCE555_ADJUSTED',
    'UP_IRRADIANCE555_ADJUSTED_QC',
    'UP_IRRADIANCE555_ADJUSTED_ERROR',
    'UP_IRRADIANCE555_DATA_MODE',
    'DOWNWELLING_PAR',
    'DOWNWELLING_PAR_QC',
    'DOWNWELLING_PAR_dPRES',
    'DOWNWELLING_PAR_ADJUSTED',
    'DOWNWELLING_PAR_ADJUSTED_QC',
    'DOWNWELLING_PAR_ADJUSTED_ERROR',
    'DOWNWELLING_PAR_DATA_MODE',
]

#
# dict for renaming parameters to crocolake names
#
params["Argo2CROCOLAKE"] = {k : k for k in params["ArgoPHY"]} # copy of the list

params["CROCOLAKE2Argo"] = copy.deepcopy(params["Argo2CROCOLAKE"])
